don't make the `project_version` editorconfig property look like a rule
KtLint tries to parse it into a Rule since it starts with the rule prefix.

```
java.lang.IllegalArgumentException: Rule with id 'kt-rules:project_version' must match regexp '[a-z]+(-[a-z]+)*:[a-z]+(-[a-z]+)*'
        at com.pinterest.ktlint.rule.engine.core.internal.IdNamingPolicy.enforceRuleIdNaming$ktlint_rule_engine_core(IdNamingPolicy.kt:17)
        at com.pinterest.ktlint.rule.engine.core.api.RuleId.<init>(Rule.kt:10)

[...]
```